[project]
authors = ["Francisco Merino-Casallo <francisco.merinocasallo@gmail.com>"]
channels = ["conda-forge"]
name = "sr-sw-dev"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = "*"
pytest = ">=8.3.5,<9"
pytest-cov = ">=6.1.1,<7"
ruff = ">=0.11.5,<0.12"
freezegun = ">=1.5.0,<2"
